### ISSUE TITLE
Suggestion: perl-version-file input support?

### ISSUE THREAD

**Issue by stefafafan** [shogo82148/actions-setup-perl#1359]
When using this action with a `.perl-version` file in the repo, I will probably do something like this:

```yml
- name: Extract perl version
  run: echo "PERL_VERSION=$(cat .perl-version)" >> $GITHUB_ENV

- name: Setup Perl
  uses: shogo82148/actions-setup-perl@v1
  with:
    perl-version: ${{ env.PERL_VERSION }}
```

It will be convenient if `perl-version-file` input was supported, something like:
```yml
- name: Setup Perl
  uses: shogo82148/actions-setup-perl@v1
  with:
    perl-version-file: '.perl-version'
```

What do you think?

Some of the other actions support this.
- https://github.com/actions/setup-node/pull/338
- https://github.com/actions/setup-go/pull/62
- https://github.com/actions/setup-python/pull/336
