### ISSUE TITLE
Please add a documented way to get a list of all supported Perl of every platform

### ISSUE THREAD

**Issue by skirmess** [shogo82148/actions-setup-perl#320]
Please add a documented way to get a list of all supported Perl of every platform. Ideally this would be a Perl module. :-)

This would allow us to dynamically create the matrix without having to edit the workflow for every repository whenever there is a newer Perl version available.

**Comment by shogo82148** [comment]
It sounds good.

My idea is the following.

```yaml
name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.perl.outputs.perl-versions }}
    steps:
    # outputs the list of 5.16 or laster versions to outputs.perl-versions
    - id: perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        list-versions: ">=5.16"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - uses: shogo82148/actions-setup-perl@v1
       with:
         perl-version: ${{ matrix.perl }}
```

Any suggestions?
