### ISSUE TITLE
shell: bash steps continue to use the system perl

### ISSUE THREAD

**Issue by skirmess** [shogo82148/actions-setup-perl#328]
On Windows, if we use `shell: bash` the `PATH` env variable always starts with `/mingw64/bin` and `/usr/bin`.

```
  job:
    runs-on: windows-latest
    steps:
      - uses: shogo82148/actions-setup-perl@v1

      # uses powershell and runs with the Perl from actions-setup-perl
      - run: perl -V

      # uses bash and runs with the system Perl
      - run: perl -V
        shell: bash
```

I can't see a way to change this behavior as the `/usr/bin` directory seems to be hard coded somehow and I'm not sure if deleting `/usr/bin/perl.exe` on Windows is a good idea? If you don't see a way to fix the path we should document that the bash shell is not supported under Windows.
