### ISSUE TITLE
update PERL5LIB for ubuntu

### ISSUE THREAD

**Issue by lskatz** [shogo82148/actions-setup-perl#456]
Hi, when I install something like `bioperl` using apt-get install, it sends the libraries outside of PERL5LIB, to `/usr/share/perl5`.  Could you update PERL5LIB to include that?  My "patch" is this step, right after the step with `shogo82148/actions-setup-perl@v1`.

```yaml
      - name: initial envs
        run:  |
          echo "PERL5LIB=$PERL5LIB:/usr/share/perl5" >> $GITHUB_ENV
```
