### ISSUE TITLE
Avoid the warning: "The strawberry distribution is not available on this platform" and "fallback to the default distribution"

### ISSUE THREAD

**Issue by szabgab** [shogo82148/actions-setup-perl#457]
I have a job like this:

```
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
        perl: [ '5.32' ]

    runs-on: ${{matrix.runner}}
    name: OS ${{matrix.runner}} Perl ${{matrix.perl}}

    steps:
    - uses: actions/checkout@v2

    - name: Set up perl
      uses: shogo82148/actions-setup-perl@v1
      with:
          perl-version: ${{ matrix.perl }}
          distribution: strawberry
```
I get a warning from GA "The strawberry distribution is not available on this platform" and also "fallback to the default distribution" for Linux and Mac.

Duplicating the step and using conditions helped me avoid the warnings

```
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
        perl: [ '5.32' ]

    runs-on: ${{matrix.runner}}
    name: OS ${{matrix.runner}} Perl ${{matrix.perl}}

    steps:
    - uses: actions/checkout@v2

    - name: Set up perl
      if: ${{ startsWith( matrix.runner, 'windows-' )  }}
      uses: shogo82148/actions-setup-perl@v1
      with:
          perl-version: ${{ matrix.perl }}
          distribution: strawberry

    - name: Set up perl
      if: ${{ ! startsWith( matrix.runner, 'windows-' )  }}
      uses: shogo82148/actions-setup-perl@v1
      with:
          perl-version: ${{ matrix.perl }}
```

Is there a better way to avoid this warning?
