### ISSUE TITLE
ExtUtils::ParseXS Missing from Windows 5.14

### ISSUE THREAD

**Issue by theory** [shogo82148/actions-setup-perl#881]
I created this workflow:

``` yaml
name: CI
on: [push]
jobs:
  winperl514:
    runs-on: windows-latest
    steps:
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with: {perl-version: "5.14"}
      - run: perl -V
      - run: cpm install --verbose --show-build-log-on-failure --no-test --with-recommends Win32::Pipe
```

Which results in [this error](https://github.com/sqitchers/sqitch/runs/3919828824?check_suite_focus=true):

```
Error: 2021-10-17T17:57:52,5088,Win32-Pipe-0.026| Can't locate object method "new" via package "ExtUtils::ParseXS" at D:\a\sqitch\sqitch\local\lib\perl5\ExtUtils/xsubpp line 51.
315
```

It is not an issue for when I simply change `5.14` to `5.16`, which [builds fine](https://github.com/sqitchers/sqitch/runs/3919917238?check_suite_focus=true).
